name: Environment variables
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      BRANCH: main
    steps:
      - run: echo "${BRANCH}" # shellコマンド経由で呼び出し
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }} # envコンテキスト経由で呼び出し
      